// Generated by scripts/slice-pet-sheets.mjs — do not edit by hand.
import type { ImageSourcePropType } from "react-native";

/** Source frame after the ×8 nearest-neighbour upscale. */
export const PET_FRAME_PX = 256;
/** Distance between frame origins in both files (frame + transparent gutter). */
export const PET_PITCH_PX = 272;
export const PET_ATLAS_COLUMNS = 8;
export const PET_ATLAS_ROWS = 5;
export const PET_POSE_COLUMNS = 3;

/** Atlas rows. `still` holds PIC (frame 0) and FALLS (frame 1). */
export const PET_ATLAS_LAYOUT = {
  "idle": {
    "row": 0,
    "frames": 4
  },
  "walk": {
    "row": 1,
    "frames": 6
  },
  "jump": {
    "row": 2,
    "frames": 8
  },
  "push": {
    "row": 3,
    "frames": 6
  },
  "still": {
    "row": 4,
    "frames": 2
  }
} as const;

/** Column of each still pose in the poses strip. */
export const PET_POSE_COLUMN = {
  "idle": 0,
  "happy": 1,
  "sad": 2
} as const;

export type PetSheet = { atlas: ImageSourcePropType; poses: ImageSourcePropType };

/** Every species/color/accessory Andrei has drawn, keyed `sp/c/a`. */
export const PET_SHEETS: Readonly<Record<string, PetSheet>> = {
  "sp1/c1/a1": {
    atlas: require("../../../assets/pets/atlas/sp1_c1_a1.png"),
    poses: require("../../../assets/pets/poses/sp1_c1_a1.png"),
  },
  "sp1/c1/a2": {
    atlas: require("../../../assets/pets/atlas/sp1_c1_a2.png"),
    poses: require("../../../assets/pets/poses/sp1_c1_a2.png"),
  },
  "sp1/c3/a1": {
    atlas: require("../../../assets/pets/atlas/sp1_c3_a1.png"),
    poses: require("../../../assets/pets/poses/sp1_c3_a1.png"),
  },
  "sp1/c3/a2": {
    atlas: require("../../../assets/pets/atlas/sp1_c3_a2.png"),
    poses: require("../../../assets/pets/poses/sp1_c3_a2.png"),
  },
  "sp1/c2/a1": {
    atlas: require("../../../assets/pets/atlas/sp1_c2_a1.png"),
    poses: require("../../../assets/pets/poses/sp1_c2_a1.png"),
  },
  "sp1/c2/a2": {
    atlas: require("../../../assets/pets/atlas/sp1_c2_a2.png"),
    poses: require("../../../assets/pets/poses/sp1_c2_a2.png"),
  },
  "sp2/c1/a2": {
    atlas: require("../../../assets/pets/atlas/sp2_c1_a2.png"),
    poses: require("../../../assets/pets/poses/sp2_c1_a2.png"),
  },
  "sp2/c1/a3": {
    atlas: require("../../../assets/pets/atlas/sp2_c1_a3.png"),
    poses: require("../../../assets/pets/poses/sp2_c1_a3.png"),
  },
  "sp2/c3/a1": {
    atlas: require("../../../assets/pets/atlas/sp2_c3_a1.png"),
    poses: require("../../../assets/pets/poses/sp2_c3_a1.png"),
  },
  "sp2/c3/a2": {
    atlas: require("../../../assets/pets/atlas/sp2_c3_a2.png"),
    poses: require("../../../assets/pets/poses/sp2_c3_a2.png"),
  },
  "sp2/c3/a3": {
    atlas: require("../../../assets/pets/atlas/sp2_c3_a3.png"),
    poses: require("../../../assets/pets/poses/sp2_c3_a3.png"),
  },
  "sp2/c2/a2": {
    atlas: require("../../../assets/pets/atlas/sp2_c2_a2.png"),
    poses: require("../../../assets/pets/poses/sp2_c2_a2.png"),
  },
  "sp2/c2/a3": {
    atlas: require("../../../assets/pets/atlas/sp2_c2_a3.png"),
    poses: require("../../../assets/pets/poses/sp2_c2_a3.png"),
  },
  "sp3/c1/a3": {
    atlas: require("../../../assets/pets/atlas/sp3_c1_a3.png"),
    poses: require("../../../assets/pets/poses/sp3_c1_a3.png"),
  },
  "sp3/c3/a3": {
    atlas: require("../../../assets/pets/atlas/sp3_c3_a3.png"),
    poses: require("../../../assets/pets/poses/sp3_c3_a3.png"),
  },
  "sp3/c2/a1": {
    atlas: require("../../../assets/pets/atlas/sp3_c2_a1.png"),
    poses: require("../../../assets/pets/poses/sp3_c2_a1.png"),
  },
  "sp3/c2/a3": {
    atlas: require("../../../assets/pets/atlas/sp3_c2_a3.png"),
    poses: require("../../../assets/pets/poses/sp3_c2_a3.png"),
  },
};
